# Generated by Django 4.2.3 on 2023-09-03 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fllow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fllowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_you_fllowed', to=settings.AUTH_USER_MODEL)),
                ('user_fllower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_is_fllowing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
